### ISSUE TITLE
Create initial validation rules for TX_STOCK_CANCELLATION

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/OCF-XState-Validation#8]

**Comment by sachin-shrestha** [comment]
Validation checks

1. A stock issuance with a corresponding security ID must exist for the security_id variable
2. If applicable, a stock issuance with a corresponding security ID must exist for the balance_security_id variable"
3. The date of the stock issuance referred to in the security_id must have a date equal to or earlier than the date of the stock cancellation
4. The security_id of the stock issuance referred to in the security_id variable must not be the security_id related to any other transactions with the exception of a stock acceptance transaction.
5. The security_id of the stock issuance referred to in the security_id variable must be the security_id of a stock acceptance transaction that has a date before or equal to the date of the cancellation. (OPEN QUESTION - NOT TRUE FOR MANY VENDORS)
6. The dates of a stock issuance referred to in the balance_security_id variables must have a date equal to the date of the stock repurchase
7. The quantity variable must be between 1 and the quantity of the stock_issuance referred to in security_id variable
8. The quantity of the stock issuance referred to in the balance_security_id variable must be equal to the quantity of the stock issuance referred to in the security_id variable minus the quantity variable
9. The stock_class_id of the stock issuance in the balance_security_id variable must be the same as the stock_class_id of the stock issuance referred to in the security_id variable
