### ISSUE TITLE
Create initial validation rules for TX_STOCK_CONVERSION

### ISSUE THREAD

**Issue by arthur-clara** [Open-Cap-Table-Coalition/OCF-XState-Validation#9]
From https://github.com/Open-Cap-Table-Coalition/OCF-XState-Validation/wiki/06.-Stock-Conversion
1. A stock issuance with a corresponding security ID must exist for the security_id variable
2. Any stock issuances with corresponding security IDs referred to in the resulting_security_ids array must exist
3. If applicable, a stock issuance with a corresponding security ID must exist for the balance_security_id variable"
4. The date of the stock issuance referred to in the security_id must have a date equal to or earlier than the date of the stock conversion
5. The security_id of the stock issuance referred to in the security_id variable must not be the security_id related to any other transactions with the exception of a stock acceptance transaction.
6. The dates of any stock issuances referred to in the resulting_security_ids or balance_security_id variables must have a date equal to the date of the stock conversion
7. The quantity_converted variable must be between 1 and the quantity of the stock_issuance referred to in security_id variable
8. The quantity_converted variable must equal the sum of any stock issuances referred to in the resulting_security_ids variable
9. The quantity of the stock issuance referred to in the balance_security_id variable must be equal to the quantity of the stock issuance referred to in the security_id variable minus the quantity_converted variable
10. The stock class id of the stock issuances in the resulting_security_id variable must be different from the stock_class_id of the stock issuance referred to in the security_id variable
11. The stock_class_id of the stock issance in the balance_security_id must be the same as the stock_class_id of the stock issuance reffered to in the security_id variable

**Comment by sachin-shrestha** [comment]
@arthur-clara for check (8) above 
- The quantity_converted variable must equal the sum of any stock issuances referred to in the resulting_security_ids variable
I don't think this is necessarily true.  Stock don't always convert on 1:1 ratio so the resultant certificates' quantity will not add up to the quantity converted.
